### ISSUE TITLE
Add SMU Logo

### ISSUE THREAD

**Issue by jessicawheeler** [dxywill/Mania#12]
Add SMU logo to the top of each page
![image uploaded from ios](https://user-images.githubusercontent.com/19536488/28932046-c7f12f1e-783d-11e7-9c28-1611cd417d6a.jpg)

**Comment by dxywill** [comment]
Hi Jessica,
Can you make the logo image with a transparent background? it does not look very good with a white background, which conflicts our current color.

**Comment by jessicawheeler** [comment]
Hey Xinyi,

This is what Eric sent me of official logos he knows of: 
https://www.smu.edu/DevelopmentExternalAffairs/PublicAffairs/IntegratedMarketing/Logos/LyleEngineering

BUT I see you already added an SMU logo that fits well at the top of the page, so that works already and looks great- so I will close this issue.
