### ISSUE TITLE
Possible Error

### ISSUE THREAD

**Issue by jessicawheeler** [dxywill/Mania#23]
When you click create a username, yesterday the fields looked like below:

![screen shot 2017-08-12 at 1 25 05 pm](https://user-images.githubusercontent.com/19536488/29250719-1e7d8310-800d-11e7-8ca5-24e82d141196.png)
![screen shot 2017-08-12 at 1 26 23 pm](https://user-images.githubusercontent.com/19536488/29250720-203cb428-800d-11e7-8143-41844678c75e.png)

Today when I try it, it is back to normal and I don't observe what's in the images above.
Just wanted to point this out as Julie brought it to my attention and then when I tried it, I saw exactly what she was talking about.

**Comment by dxywill** [comment]
I also noticed this issue yesterday and it has been fixed
