### ISSUE TITLE
Questionnaire Page Edits

### ISSUE THREAD

**Issue by jessicawheeler** [dxywill/Mania#30]
Move "Mental State Questionnaire" down a bit more from where it says "When you check the mania option..."

Add (hline?) between each question.

Instead of "Other Information", just have the Question "Was a flash used in this photo?" with no line and make answers (yes, no, I don't know) closer space-wise.

**Comment by jessicawheeler** [comment]
Looks good!  Maybe just add a bit more space between the last checkbox for the mental state questionnaire and "Check the medications..."

**Comment by dxywill** [comment]
Added
