### ISSUE TITLE
Create Username Page

### ISSUE THREAD

**Issue by jessicawheeler** [dxywill/Mania#31]
ADD text under Pick A Unique Name:

**"Please choose a unique username so that you can upload images to our system multiple times. Please DO NOT use your real name as your username. The username you choose should not reveal anything about you, but should be something you can remember. It could be as simple as a number of your favorite word. If you forget your username, there is no way to look it up, simply create a new one."**

-UNDER "Already have a username?  Sign in", ADD:
**"Please DO NOT use the back button on browser.  To return to the Homepage, click the link below."**

**Comment by jessicawheeler** [comment]
Please switch where the texts currently are - place "please choose a unique username..." where you currently have "Please DO NOT..." and "Please DO NOT.." Where "please choose a unique username..." is.

**Comment by dxywill** [comment]
Actually thats Eric's opinion...

**Comment by jessicawheeler** [comment]
Oh ok sure!  Let's just leave it then, thank you
