### ISSUE TITLE
django login settings

### ISSUE THREAD

**Issue by eclarson** [dxywill/Mania#38]
change to renew session with every page change on image upload

**Comment by dxywill** [comment]
There is a switch called " SESSION_SAVE_EVERY_REQUEST ", set it to True will renew the session on each request. However, it conflicts our current mechanism used for session expired notification. Our current method is every 30 secs, an ajax request is sent out to the endpoint /collection/session to get the info if the current session stored in our DB is expired. If we turn "SESSION_SAVE_EVERY_REQUEST" on, it will renew the session every 30 sec, that means the session will never expire until the browser is closed. Solutions do exist to overcome this issue, we could customize the session middleware used by django, but I think it may be a little bit too much? We could simply increase the session alive time to 30mins or may be an hour?

**Comment by eclarson** [comment]
leave it at 15 minutes, then. I think.
